### ISSUE TITLE
Access to the recource is forebidden

### ISSUE THREAD

**Issue by SergiyVV** [migueesc123/PowerBIRESTAPI#10]
Hi Miguel,
That's me again.

Regarding 'Get Datasets In Group' API:
https://api.powerbi.com/v1.0/myorg/groups/{groupId}/datasets

There are workspaces that don't have Datasets tab
![NoDatasetTab](https://user-images.githubusercontent.com/52447998/63346483-bf473300-c35d-11e9-9662-1088ecda25bd.png)
The workspace on the screen above was created when a user got access to a certain Teams tab. A user has Member permissions for this tab. 

When I use 'Try It' tool for a workspace with Datasets tab absent:
https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/getdatasetsingroup
I get Response Code: 403:
![TryItJson](https://user-images.githubusercontent.com/52447998/63347262-6bd5e480-c35f-11e9-84ae-1e2aeb793603.png)

That's why when PowerBIRESTAPI connector runs 'Get Datasets In Group' API it experiences the same problem:
![NavTable](https://user-images.githubusercontent.com/52447998/63347757-76dd4480-c360-11e9-9f34-4cf375207a35.png)

Here is the code line where API gets called:
![Code](https://user-images.githubusercontent.com/52447998/63347819-9bd1b780-c360-11e9-9104-537155c75c05.png)

**Comment by migueesc123** [comment]
I wish that I could change something about this, but this is one of the "by design" choices that the MSFT team took.
The connector just provides the same message that the API is providing. It would better if the API sent us a specific "null" response, but it just sends us a "40x" and we can't create a specific rule against a "40x" rule as that goes against best practices and it would create some really bad consequences with other resources that do provide a "40x" response that actually means that they don't have access to it.

**Comment by SergiyVV** [comment]
The user whose account I used for testing the connector has dozens of datasets and as you see it's not possible to get an info on ANY of them.
>we can't create a specific rule ... as that goes against best practices

Without handling the error I mentioned those who face it won't be able to use the connector.
Actually, there are other cases that need handling. For example:
![OtherCases](https://user-images.githubusercontent.com/52447998/63422320-cda35680-c412-11e9-9eeb-965c60a970b9.png)

**Comment by migueesc123** [comment]
@SergiyVV I completely understand where you're coming from, but on top of my head I'm not able to think of a way that wouldn't compromise the rest of the connector.
The Custom Connector has been designed to be used by the Admin of the tenant who has access to the full experience, so these type of errors shouldn't really happen for those users.
Adding an error handling situation with "try" (for example), could create unexpected results. 
Again, this is a situation caused by the definition of the API and not because I wanted this to happen.

If you happen to have any idea on how to tackle this in an efficient and secure fashion, please let me know.

**Comment by SergiyVV** [comment]
@migueesc123 , ok.

Thank you for the job done. A unique one.
