### ISSUE TITLE
please add a new function pos

### ISSUE THREAD

**Issue by jasonlaw997** [migueesc123/PowerBIRESTAPI#112]

**Comment by jasonlaw997** [comment]
hi,
I want to query something in dataset (Datasets - Execute Queries In Group)
but this connector did not had the post action
Would you add that,please?many thanks!

**Comment by migueesc123** [comment]
Hey! I'm adding the tag so that people can see the request, but I personally don't have the bandwidth for this and I'm not even sure if I'll come to review this connector this year.

I'll let other contributors chime in, but don't forget that this repo is under the MIT license, so you are free to fork, clone or even contribute to this repo.

**Comment by klinejordan** [comment]
Thanks to @tirnovar this is now available in the latest version. Thanks!
