### ISSUE TITLE
getreportusers as admin

### ISSUE THREAD

**Issue by sarava8304** [migueesc123/PowerBIRESTAPI#115]
can we have the getreportusers as admin api, to track for whom the dashboards has been shared. (who are all accessed the dashboards)

**Comment by klinejordan** [comment]
Logging this as an enhancement request, but in large tenants this will take a long time to complete so its likely going to go into the Experimental folder. Looping through thousands of reports individually 

The best place to get this information is the scanner API, which is difficult to incorporate into this connector because it uses a polling mechanism to retrieve results and M is not the best language for doing those kind of operations. 

And just to clarify, you're looking for Get Report Users As Admin? If so, that's not going to give you information on who has access to Dashboards, it will give you information on to whom the Report is shared.

**Comment by klinejordan** [comment]
Added Item user queries to experimental folder
