### ISSUE TITLE
Certification status

### ISSUE THREAD

**Issue by Sh5678** [migueesc123/PowerBIRESTAPI#138]
Hi Miguel -- Considering your current role in Microsoft, can we get this Rest API Connector certified and made available within the connector library?

**Comment by migueesc123** [comment]
hey! only the owner of the data source can certify the connector :) I'd need to move from the current role to be the owner of the Power BI REST API in order to make that happen, but the best course of action is that you post your idea on the ideas.powerbi.com site or reach out directly to the Product managers of the power bi team to send them this request
