### ISSUE TITLE
all power bi user data

### ISSUE THREAD

**Issue by willvon** [migueesc123/PowerBIRESTAPI#15]
Hello, how are you? Congratulations for the work, it was very good. Does this connector only bring data related to the logged in user? Not bringing all the data from the entire Power BI service environment?

**Comment by migueesc123** [comment]
Hey! 
Ideally this is something a custom connector for the admin of the tenant, but I believe that anyone wth the right access should be able to use the API. It's more related to how you set up the Web application - the whole role and permissions and how the API actually works.

I haven't tried this custom connector without any admin access, so if you end up trying it do let us know how it goes!

Also, here's the official documentation for the Power BI REST API:
https://docs.microsoft.com/en-us/rest/api/power-bi/

Best,

**Comment by klinejordan** [comment]
You can just use the GETData function to call the Admin APIs - there are no specific tables built in the custom connector for the admin end points (although I could probably add some easily).

The GetGroupsAsAdmin is probably the best starting point, since it supports $expand operations for users, dashboards, reports, dataflows and datasets. No data sources unfortunately. To make that API call just invoke the GETData function with "admin/groups?$top=5000" as the input (5000 is the maximum records returned by the API, but you can use skip to loop through all of them). 

Also keep in mind you do have to have the Power BI Service Administrator role in Azure AD in order to call the admin APIs - you cannot use a service principal or a user with non-elevated permissions.

**Comment by klinejordan** [comment]
I just pushed a new version that includes explicit queries against the Admin APIs.

I included data source level details because it works, but be advised that this does not scale with large tenants as the API has to loop through every datasource individually instead of using $expand.
