### ISSUE TITLE
Admin - Datasets GetDatasourcesAsAdmin

### ISSUE THREAD

**Issue by bsaragadam** [migueesc123/PowerBIRESTAPI#23]
Admin - Datasets GetDatasourcesAsAdmin

While calling this API from the custom connector its failing to fetch the DatasourceID and gateway ID and shows as the error message. 

![image](https://user-images.githubusercontent.com/56641802/72796764-e89a2100-3c65-11ea-89f9-b3979c2f74b0.png)

![image](https://user-images.githubusercontent.com/56641802/72796858-18492900-3c66-11ea-9e3c-e1932727ddc5.png)

 I tried with online  Power BI REST API try now 

https://docs.microsoft.com/en-us/rest/api/power-bi/admin/datasets_getdatasourcesasadmin#code-try-0

Tried but its has 3 records and showing only 2 records. 

{
  "@odata.context": "http://wabi-west-us-redirect.analysis.windows.net/v1.0/myorg/admin/$metadata#datasources",
  "value": [
    {
      "datasourceType": "Sql",
      "connectionDetails": {
        "server": "YYYYYYYYY",
        "database": "finance"
      },
      "datasourceId": "4ce43ae2-2316-46ae-bd7e-94831d7e8003",
      "gatewayId": "5adf17b9-f7ae-40c0-902e-ac93f0a57c2c"
    },
    {
      "datasourceType": "Sql",
      "connectionDetails": {
        "server": "YYYYYYYY",
        "database": "shared"
      },
      "datasourceId": "162e83d0-035f-400f-b406-0556bd23b227",
      "gatewayId": "5adf17b9-f7ae-40c0-902e-ac93f0a57c2c"
    },
    {
      "datasourceType": "Sql",
      "connectionDetails": {
        "server": "YYYYYY",
        "database": "finance"
      }
    }
  ]
}

**Comment by bsaragadam** [comment]
@migueesc123 FYI.. I think its a bug from Microsoft.. I have opened the support ticket with them,

**Comment by klinejordan** [comment]
I contributed the Admin part of this connector, and to be honest, this call never really worked for me because my tenant (12,000+ datasets) is too big and the results never returned. 

Keep me in the loop on what Microsoft says, i was only able to get this to work in a sandbox environment with only a few datasets and wouldn't be surprised if there's some datasets that don't return a datasourceID, in which case we have to update the Power Query behind this API call to account for JSON returns that don't include the expected columns.

**Comment by klinejordan** [comment]
@bsaragadam any update from Microsoft?

**Comment by kazimrajani** [comment]
Power BI Service Admin API and Functions are not working for me at all. It asks me to sign in and then errors out saying authentication error. I have the Power BI Administrator role assigned to my user account and still getting this error. I am unsure if its because of MFA enabled on my account due to a bug as [described here](https://github.com/microsoft/powerbi-powershell/issues/135).

![image](https://user-images.githubusercontent.com/26996047/75346093-e8cab380-58d8-11ea-9600-2dd5eabedd2a.png)

**Comment by Oddjobe** [comment]
> t asks me to sign in and then errors out saying authentication error. I have the Power BI Administrator role assigned to my user

Hi @kazimrajani ! 
Have you "Granted consent" in API Permissions (Azure AD/App registrations) ?
![image](https://user-images.githubusercontent.com/15087494/76246182-7e513600-623d-11ea-9296-fdf1ee2c4276.png)

**Comment by kazimrajani** [comment]
Hi @Oddjobe 
Thanks for the comment, I'll check with my infra team.
Thanks
kaz

**Comment by oex-pbi** [comment]
> Power BI Service Admin API and Functions are not working for me at all. It asks me to sign in and then errors out saying authentication error. I have the Power BI Administrator role assigned to my user account and still getting this error. I am unsure if its because of MFA enabled on my account due to a bug as [described here](https://github.com/microsoft/powerbi-powershell/issues/135).
> 
> ![image](https://user-images.githubusercontent.com/26996047/75346093-e8cab380-58d8-11ea-9600-2dd5eabedd2a.png)

Similar to @kazimrajani - I cant get access to any Admin tables, even though Admin Consent has been granted in Azure

![image](https://user-images.githubusercontent.com/54525999/79693454-a67f7c00-8262-11ea-9f84-0e7fba43174e.png)

As you can see - admin has been granted, and other tables work OK 

![image](https://user-images.githubusercontent.com/54525999/79693473-c747d180-8262-11ea-9290-070e5b4ce529.png)

![image](https://user-images.githubusercontent.com/54525999/79693489-e0e91900-8262-11ea-9623-459b7520a680.png)

**Comment by klinejordan** [comment]
@oex-pbi When you go to the admin portal in the Power BI service, do you see the below options? Sometimes the role can be assigned but if your org is using Privileged Identity Manager you need to activate the role each time. If you don't see these options in the Admin Portal menu, your role isn't activated
![image](https://user-images.githubusercontent.com/48561922/79765413-71634000-82db-11ea-8970-ce481d2ee888.png)

The real test for this is if you can make the admin API calls in Postman using the app registration client id/secret and your username/password then you will be able to use this custom connector. But if you're unable to make the calls in Postman then you won't. I've attached a postman collection with the sensitive information for my tenant removed but you should be able to use this to test. 
[PBI Activity Logs.postman_collection.zip](https://github.com/migueesc123/PowerBIRESTAPI/files/4504404/PBI.Activity.Logs.postman_collection.zip)

**Comment by oex-pbi** [comment]
Many thanks @klinejordan the issue seems to be with MFA on the account. The account is Global Admin and Power BI Admin, so yes I see the Admin settings etc.

![image](https://user-images.githubusercontent.com/54525999/79770360-34bc3680-8325-11ea-9858-4ba4e41a2622.png)

Any advice for handling MFA scenarios, as this cannot be disabled on this account

**Comment by klinejordan** [comment]
My account is MFA enabled and I have no issues calling the Admin APIs in both Postman and using this connector. Were you able to try to the Postman collection?

**Comment by oex-pbi** [comment]
Hi Jordan - Unfortuantely not, may just be my lack of experience with Postman I'm afraid - I'm only used to calling the APIs typically from ADF and Logic Apps - or from the 'Try it' feature on the PBI docs.

The example I normally use in Postman is as per below - method used is more straightforward - and i get this error:

![image](https://user-images.githubusercontent.com/54525999/79775361-08f07f00-832c-11ea-9ec1-b2c51f3ccc27.png)


There seems to be multiple requests in your example, it would be most helpful for you to advise where you would enter these details in Postman, such as a screenshot - I added the entire JSON to the raw section, updated the bearer token and entered crednetials, doesnt look like it wants to run

Or if you are available for 1:1 correspondance email me direct?

**Comment by joeywas** [comment]
Connect-PowerBiServiceAccount was working (about 7 days was when i was still using it) when authenticating with credentials that required MFA -- now results in errors:

Connect-PowerBIServiceAccount : Failed to get ADAL token: Unhandled Exception: System.AggregateException: One or more errors occurred. ---> 
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalClaimChallengeException: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use 
multi-factor authentication to access
