### ISSUE TITLE
Failed to save modifications to the server.

### ISSUE THREAD

**Issue by Oddjobe** [migueesc123/PowerBIRESTAPI#28]
Hi Team,
I'm getting this error when i "Close and apply" to load/import the data?
Something anyone faced?
It doesn't matter what table I try to import.

**Failed to save modifications to the server. Error returned: 'Expression in partition 'n/a' in table 'n/a' references unknown variable or function 'PowerBIRESTAPI.Navigation'.
 '.**

Step1
![image](https://user-images.githubusercontent.com/15087494/76399200-8664bf00-637e-11ea-9a7a-893ef346c320.png)

![image](https://user-images.githubusercontent.com/15087494/76399074-4ef61280-637e-11ea-851a-a7c53bf77103.png)

**Comment by migueesc123** [comment]
it appears that your .mez is not properly setup. I'm not exactly sure what could be wrong, but the "unkwon variable or function" refers to the custom connector not being recognized, so I'm wondering how you're even getting to the Navigator window.

**Comment by Oddjobe** [comment]
Hi @migueesc123! Any thoughts? I would really like to get this working.
Thanks

**Comment by migueesc123** [comment]
@Oddjobe Could you share a step by step on how to reproduce this ? Starting from how did you set up your mez file and assuming that your app has all the right permissions

**Comment by Oddjobe** [comment]
Hi Miguel,
I followed the steps provided very carefully. 
I didn't have the "custom connectors" folder so I did create that and gave it full permission to folder and subfolders.
We could have a quick Teams call if you like and have the time.
Thanks!

**Comment by migueesc123** [comment]
Hey!
I was able to follow the step by step provided by the repo and make it work on a completely new tenant and computer without any issues.

Have you been able to reproduce this error on a different machine? If yes, could you please provide the exact step by step that you followed in that other machine to get the same error?

We basically need a written step by step on what you did in order to reproduce the error. From there we can figure out if it has to do with the Custom Connector itself or if perhaps it's something out of our reach like the Power BI Desktop code or how you've set up your own Web Application. 

My best guess is that it has something to do with the credentials that you've used which appear to be incorrect or have changed. You can look at a case that had almost the same error message [here (url)](https://community.powerbi.com/t5/Desktop/failed-to-save-modifications-to-the-server-Error-returned-OLE-DB/td-p/384890).

The support for this repo is only for the code of the custom connector and is provided only via this issue section by volunteers without any warranties of any kind.

My company does provide extended support for Power BI Custom Connectors that I've been a part of in the event that you'd like to acquire our services and schedule a 1:1 meeting to troubleshoot or extend the custom connector in any way.  If you'd like to inquire about our remote consulting services you can reach us at info@poweredsolutions.co

**Comment by migueesc123** [comment]
@Oddjobe  Please read this https://github.com/migueesc123/WooCommerceConnector/issues/11#issuecomment-603593772
