### ISSUE TITLE
Different Sets of Data Columns When Invoking Different Dates Ranges

### ISSUE THREAD

**Issue by 7rujerry** [migueesc123/PowerBIRESTAPI#36]
**When I perform this action:**    

    let
    
    Source = #"Event Activity Log"(#date(2020, 5, 29), #date(2020, 5, 29))
    
    in
    
    Source

**These columns get returned:**

`{"Id", "RecordType", "CreationTime", "Operation", "OrganizationId", "UserType", "UserKey", "Workload", "UserId", "ClientIP", "UserAgent", "Activity", "IsSuccess", "RequestId", "ActivityId", "ExportEventStartDateTimeParameter", "ExportEventEndDateTimeParameter"}`

**However when I perform this action:**

    let

    Source = #"Event Activity Log"(#date(2020, 5, 18), #date(2020, 5, 29))

    in

    Source

**These columns get returned:**

`{"Id", "RecordType", "CreationTime", "Operation", "OrganizationId", "UserType", "UserKey", "Workload", "UserId", "ClientIP", "UserAgent", "Activity", "ItemName", "WorkSpaceName", "DatasetName", "ReportName", "WorkspaceId", "ObjectId", "DatasetId", "ReportId", "EmbedTokenId", "IsSuccess", "ReportType", "RequestId", "ActivityId", "DistributionMethod", "ConsumptionMethod"}`

**Comment by migueesc123** [comment]
Hey!
Thank you for trying out the connector. Could you confirm that you get those columns from thet API when using other methods to query the API?

The connector doesn't hardcode any column names, so it does its best to just show the user whatever fields it received from the API and it does this to future-proof itself in the event that the API adds new columns in the future. 

In this case, the connector only received those columns when it queried the API for those dates. I'm curious if in your 2nd call you got data for those new columns on may 29th or if they're just filled with null values.
 
However, the connector wasn't designed to handle assymetrical responses, so that might be something that I could look at in the future to improve the connector.
You can also customize the connector to your specific needs and environments. This repo is under the MIT license. You can read the license here: https://github.com/migueesc123/PowerBIRESTAPI/blob/master/LICENSE

**Comment by klinejordan** [comment]
The activity events end point returns different array entities and values depending on the types of activities in the date range

**Comment by migueesc123** [comment]
thanks, @klinejordan ! 
Then I need to update my code to take care of that. Currently it'll pick the first array and use that set of fields to define the records. This is natively how Table.FromRecords works over a list of records - it infers that all of the records are the same.

I'll make a change to the code in the next few weeks if time allows.

**Comment by 7rujerry** [comment]
> Hey!
> Thank you for trying out the connector. Could you confirm that you get those columns from thet API when using other methods to query the API?
> 
> The connector doesn't hardcode any column names, so it does its best to just show the user whatever fields it received from the API and it does this to future-proof itself in the event that the API adds new columns in the future.
> 
> In this case, the connector only received those columns when it queried the API for those dates. I'm curious if in your 2nd call you got data for those new columns on may 29th or if they're just filled with null values.
> 
> However, the connector wasn't designed to handle assymetrical responses, so that might be something that I could look at in the future to improve the connector.
> You can also customize the connector to your specific needs and environments. This repo is under the MIT license. You can read the license here: https://github.com/migueesc123/PowerBIRESTAPI/blob/master/LICENSE

That's the interesting part! Is that in my second call, it doesn't return nulls. There's actually data that is being recorded behind the scene that's not being included in the first call such as (WorkspaceId, DatasetId, ReportId, etc...)

**Comment by migueesc123** [comment]
Hey!
I've modified the function so it can handle assymetrical responses.

Thank you for reporting this!
