### ISSUE TITLE
Connecting Using Instructions

### ISSUE THREAD

**Issue by daedramagic** [migueesc123/PowerBIRESTAPI#44]
When connecting to the API with the given instructions. I do get the sign in prompt then right after that I get the following error. 
![image](https://user-images.githubusercontent.com/68972343/88853958-66a32b80-d1a5-11ea-956b-ba9b71229e6b.png)

**Comment by migueesc123** [comment]
Hey! 
The error that you're seeing is usually caused by your web application not having the correct scope or perhaps your mez file not having the correct set of clientId and clientsecret.

I'd recommend reviewing the documentation available on our reader file to check that you have all the pieces needed to make your connector work.

Unfortunately, issues related to the web app or its configuration are out of the scope of the support of this repo since they rely heavily on how your own tenant configures it.

If you encounter any issues at the custom connector level, like values coming out as errors or incomplete data, please open a new issue for it.

Should you require further assistance or custom development on your connector, my company Powered Solutions provides support on this and many more connectors. You can contact us at info@poweredsolutions.co for a quote.

Best!
