### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by vsslasd** [migueesc123/PowerBIRESTAPI#48]
Great idea - this connector. It's something that is missing in PowerBI. 
Unfortunately, we cannot utilize it yet... is there a newer version ? 
We went through the steps a number of times with Microsoft and kept running into the same issue. 
when trying to attach to any of the database objects, we get error messages. including: "We couldn't authenticate with the credentials provided. Please try again."

We have tried this using various credentials, without avail. 

Any thoughts on how to resolve ?

**Comment by migueesc123** [comment]
Hey! 
Could you provide a set of steps to reproduce the issue?

If the application says that you couldn’t authenticate, that might be sign that there are some missing scopes to be enabled at your application, but nothing that we can control at the custom connector level.

**Comment by marcmahmoodivc** [comment]
Hi Miguel, 

Great Custom Connector; thank you!

I am able to access details on Workspaces / reports etc. without any problems using the custom connector.

Unfortunately I too am unable to access the "Event Activity Log" due to permissions.  I suspect my account would require Tenant Level Audit Log reads rather than my Power BI Service Admin permissions which (in theory) enable me to read Power BI specific Audit Log entries only...

Kind regards,

Marc
![PBIDesktop_ecCLpCppWx](https://user-images.githubusercontent.com/58337086/102112903-4ad8b300-3e30-11eb-9a2a-fbf36662b0d9.png)
![PBIDesktop_HTrIUhBjpf](https://user-images.githubusercontent.com/58337086/102112927-53c98480-3e30-11eb-8b71-3fc7a4aa063d.png)
![PBIDesktop_mD5AOrocWY](https://user-images.githubusercontent.com/58337086/102112984-63e16400-3e30-11eb-8958-e326abdbd420.png)

**Comment by migueesc123** [comment]
Resolved outside of GitHub. Couldn't determine the root cause or repro the issue, but the current instructions of the repo worked perfectly.

**Comment by marcmahmoodivc** [comment]
Hi Miguel,

Thank you for your help on this; I managed to resolve it and learnt a lot along the way:

- for those unable to see the Custom Connector in PBI desktop, make sure you add it to the correct folder if you have OneDrive redirection set up (for me I had to go to C:\Users\<username>\OneDrive - <company name>\Documents\Power BI Desktop\Custom Connectors)
- 
- the API permission Tenant.Read.All (whose name scared the crap out of our Security team) has a very small grayed out button at the top titled "Grant admin consent for <company name>" which only a Tenant admin can click or see properly.  As a Power BI Service Admin, I did not realise this!

It's all working now and is a great time saver and simplifier of the whole process.

Thanks again,

Marc

**Comment by peterkalk** [comment]
I've had the same problem after following the installation instructions: No access to the admin API's. Error message: "We couldn't authenticate with the credentials provided". After trying a lot of possible solutions I did the following and this solved the problem (I only had Application permission for Tenant.Read.All and no delegated permission):
1. Go to Azure Active Directory -> App registrations and choose your Power BI API App. 
2. Go to the Api permissions tab
3. Add Api permissions and choose Power BI Services
4. Add delegated permissions for Tenant.Read.All
5. Grant the permissions

This worked for me!
