### ISSUE TITLE
Data extraction issues with AAD connector

### ISSUE THREAD

**Issue by Chris-Burgess-ACTGOV** [migueesc123/PowerBIRESTAPI#52]
Hey Miguel
Cannot seem to get the new connection method to bring back data.

Am logged in to PBI and Windows with aad account that has PBI Service admin rights (additionally my colleague has done same, with same results and his aad is a PBI tenant admin. So between the two of us we should have the necessary access to extract the data.

Have not unzipped/adjusted the mez file.

**Functions**
![image](https://user-images.githubusercontent.com/60373199/109229363-4ad53600-7817-11eb-89b1-4316882a736d.png)
First issue is the GETDATA not displaying and data through the connector ui (Navigator)

**Gateways** appear to load successfully

**Personal**
 
![image](https://user-images.githubusercontent.com/60373199/109229679-c0410680-7817-11eb-95b7-3ab54c726332.png)
if no app or dashboard or tile or report (or dashboard does not have an associated report source) in personal workspace code fails. This would be a low use case but causes breakage?

**Service Administrator**
Data loads through the navigator

So for this issue im loading the getdata and all the administrator queries

![image](https://user-images.githubusercontent.com/60373199/109230373-def3cd00-7818-11eb-95fa-bc3a03670066.png)
I have disabled the getdata so i can get the other queries into DAX

Appears to be loading the data
![image](https://user-images.githubusercontent.com/60373199/109230508-1b272d80-7819-11eb-914d-878265e54230.png)

Then boom they all error out
Eg (error for each query is same)
"Capacities (Admin)
Failed to save modifications to the server. Error returned: 'OLE DB or ODBC error: [Expression.Error] The field 'datasourceId' of the record wasn't found.. '."

As i alluded my colleague has exactly same issue with his tenant admin account so dont think its a permissions thing?

Any guidance appreciated.

Thanks and really appreciate  the work you have done here to get this custom connector out there!!!

Cheers

Chris

**Comment by Chris-Burgess-ACTGOV** [comment]
Update: Found a corrupt dataset datasource on my end. [loaded each PQ until i got the one breaking]
This explains why load is failing. My issue for this is now to find the Workspace that the dataset is in as PQ cannot go past the 'corrupt' record. (Remove errors doesnt work here as the record is not correctly formed?)
![image](https://user-images.githubusercontent.com/60373199/109249949-ceede480-783c-11eb-91b1-1ff807037fba.png)

So distilling all the above I still have a GETDATA issue and the Personal WS contents failing if there is not a object to harvest.

**Comment by klinejordan** [comment]
Thanks for the feedback Chris, although it'd be great if these could separate issues because they may not all get fixed at once. 

Get Data will not work if you don't provide a parameter. Not sure why the parameter is marked as optional but AFAIK its always required some relative path in the API to return anything. Miguel can probably provide more details here as I did not contribute to this. 

The Personal workspace stuff is an edge case for sure but it's probably a good idea for all of these queries to get List.IsEmpty checks. I'm guessing it would be a low priority for any contributor since you don't have to include this query in a dataset if it doesn't return records, or the queries can be disabled. 

As for the admin issue (this was my primary contribution to this repository),  I'm guessing the "corrupt" dataset you're seeing is just one that doesn't have datasources, which is also an edge case but can certainly happen. 

Its likely this will require some effort to fix, but  the datasources queries have never really been reliable since the APIs perform extremely poorly and are very difficult to test, at least for me. My tenant (~60,000 workspaces) is so big these never work in PBI Desktop, and it takes a custom app a full 15 hours for those queries to finish since the API calls are throttled every hour and tokens expire in an hour too. To be honest I debated even including them in this custom connector because the performance is so bad. These queries are written against the old GetGroupsAsAdmin and GetDatasetDatasources/GetDataflowDatasources end points and the new ones are faster but require POST operations in addition to GET operations and polling, neither of which are very Power Query friendly. 

I'll try to take a stab at the admin one when I get the chance, but you know, day job and all that :)

**Comment by Chris-Burgess-ACTGOV** [comment]
Hey Jordan
Thanks for the update/intel!!
The wonders of data extraction :) 

I dont think the admin issue is caused by a dataset without a datasource (like the personal). Really think its a corruption in the tenancy data as PQ bugs out on that record.

Now back to the day job!!

CB

**Comment by migueesc123** [comment]
> Get Data will not work if you don't provide a parameter. Not sure why the parameter is marked as optional but AFAIK its always required some relative path in the API to return anything. Miguel can probably provide more details here as I did not contribute to this.

You are correct. I primarily did it that way so the function could be exposed as part of the global environment. In other words, you can just type ```PowerBIRESTAPI.GETData``` in your formula bar and it'll recognize the function. The alternative would be to set it with a required parameter, but then you won't be able to find to function like I just mentioned. The only way would be to find the function by calling first the ```PowerBIRESTAPI.Navigation``` and then navigation to that specific function. That's essentially how I implemented the function for the Event Activity Log.

Would that behavior be good enough for you @Chris-Burgess-ACTGOV ?

In regards to the rest of the concerns raised, they are all valid.  You're completely welcome to contribute, change the code as you see fit and send us a PR so we can review it.

My goal is that this can gain enough traction so that it ends up in MSFTs radar so this can, at a later date, become an official certified connector which would require me to re-write a lot of the code to meet the certified connectors standards.

**Comment by klinejordan** [comment]
Closing this issue as I've added some error catching for datasets with no data sources. I don't have the time right now to address how to handle empty JSON payloads but will keep that in mind for the next time I'm able to open up the hood. Thanks!
