### ISSUE TITLE
Problem: datasources of datasets (Admin)

### ISSUE THREAD

**Issue by nes0911** [migueesc123/PowerBIRESTAPI#55]
Hello Miguel,

First!!! Congratulate for you extraordinary work. I comment on the following problem when trying to obtain the data sources of data sets (Admin), apparently a Timeout is presented and the following error returns.

![image](https://user-images.githubusercontent.com/37044151/115607084-e5ec0880-a2ba-11eb-8a61-30f7655bbf70.png)

![error](https://user-images.githubusercontent.com/37044151/115607118-f1d7ca80-a2ba-11eb-9e2d-913f1b258e04.png)

**Comment by migueesc123** [comment]
Hey!
That could be because of this line:
https://github.com/migueesc123/PowerBIRESTAPI/blob/b753bba38fb5f9e21a24bac91f76f485685d1d70/Power%20BI%20API/Power%20BI%20API/PBIAPI.pq#L632

I'm able to repro, but I won't have time to get to it for the next couple of months :(

@klinejordan would you mind taking a look at this one, please? If not, we can remove it from the connector until we have a fix.

@nes0911 the best workaround would be for you to use the more Generic functions to query the data from the REST API such as the "GETData" function or modify the custom connector to your specific needs.

**Comment by nes0911** [comment]
Hi,

I'm removing not-so-needed columns that correspond to that module and performing other tests. If I find any possible solution, I share it in this way.

	PowerBIRESTAPI.DatasetDatasourcesAsAdmin = () =>

Thank you!!!

**Comment by klinejordan** [comment]
I'm also able to repro in medium and large tenants, but the timeout isn't due to the connector it is due to the API. The way to get this data now is to use the new [GetWorkspaceInfo APIs](https://docs.microsoft.com/en-us/rest/api/power-bi/admin/workspaceinfo_getmodifiedworkspaces), which would be a challenge to create in a custom connector for Power BI Desktop since they involve incremental pulls and polling. 

These calls in the connector works flawlessly for small tenants but even medium size tenants will struggle with this API. It throttles to 60 requests per hour (this is likely where the timeout happens). In my tenant, looping through all 30,000 datasets with a Logic App I built takes about 15 hours. 

I debated including this query in the connector when I made it knowing it wouldn't work for many tenants and at this point I'm thinking we should take it out. It's really meant for retrieving the data sources from a single dataset, not for pulling the datasources of every dataset en masse. The new APIs are much better suited to this task.

**Comment by klinejordan** [comment]
I am working on a PR that will move the Dataset Datasources (Admin) and Dataflow Datasources (Admin) queries to a new "Experimental" folder since we cannot guarantee performance of that API call

**Comment by ansariahmed96** [comment]
Hi, I tried to use this as well and realized I am also facing the same issue. I was referred by Microsoft to use this REST API to get our organizations data and was wondering if there is a workaround for the time being?

**Comment by klinejordan** [comment]
That's interesting that Microsoft told you to use this custom connector as that would be a first AFAIK. Are you sure they didn't tell you to use the REST API? Remember that this custom connector just leverages the Power BI REST API. This custom connector, right now, is not an official Microsoft offering. The Power BI REST API is. 

As I've said in previous comments on this thread, the GetDatasourcesAsAdmin **does not scale well in even medium size tenants.** It is why we've moved it into an "Experimental" folder in the custom connector navigation as we cannot guarantee the performance of this API in every tenant. Microsoft can't either. 

You will need to use the newer GetWorkspaceInfo API to get data source information for datasets and dataflows: https://docs.microsoft.com/en-us/rest/api/power-bi/admin/workspaceinfo_getmodifiedworkspaces. Using this API is significantly more complex than the older admin APIs and it would take significant work to include in this connector, if it can even be accomplished.

**Comment by ansariahmed96** [comment]
Gotcha, thanks I'll take a look into the newer GetWorkspaceInfo API to get the sources.
