### ISSUE TITLE
Certification?

### ISSUE THREAD

**Issue by jarretluft** [migueesc123/PowerBIRESTAPI#70]
Hi,
Thanks for the custom connector, it looks promising though I haven't tried it yet because it is uncertified and I don't think my organization will allow that on our gateway.
Have you considered trying to get it certified by MS for inclusion directly in PowerBI?

Cheers,
J.

**Comment by migueesc123** [comment]
Hey J.

Unfortunately, only the owners of the data source are allowed to go through the certification process. This means that only Microsoft can make that happen. I've tried to convince them, but to no avail since I'm only one person.

I'd highly encourage you to voice your suggestion directly to Microsoft via whatever channel you see fit.

In the meantime, I do see a lot of companies making an exception only for this custom connector alone as it's by far the easiest way to consume the Power BI REST API with the context of having to load the data into Power BI Desktop.

Best!

**Comment by jgibbycsc** [comment]
In case anyone comes across this thread (unlikely), click here and vote:

https://ideas.powerbi.com/ideas/idea/?ideaid=fcb9461d-a747-4a3e-9b46-6bd8fa1e79fb

Thanks @klinejordan for posting the Power BI idea, as much as I dislike having to use the Idea system..
