### ISSUE TITLE
GetGroupsAsAdmin with GETData

### ISSUE THREAD

**Issue by nonnsi** [migueesc123/PowerBIRESTAPI#8]
Hi, thank you for your work! It's great.

I have one problem, the users column in the Workspacess List is null for all the workspaces so I'm trying to use the GETData function to GetGroupsAsAdmin by writing:

= GETData("admin/Groups?$top=5000%26$expand=users")

I get the error message:
"We couldn't authenticate with the credientials provided. Please try again."

I'm using the admin credentials and it works on this site:
https://docs.microsoft.com/en-us/rest/api/power-bi/admin/groups_getgroupsasadmin#code-try-0

by writing $top: 5000
                 $expand: users

Is it not possible to get data with the admin api?

Thanks,
Jon

**Comment by migueesc123** [comment]
I think that the issue here is that you're mixing encoders and non-encoding characters. the %26 should be a &
![image](https://user-images.githubusercontent.com/9544580/61712848-d6721100-ad1c-11e9-9d67-3716f66b90f7.png)
Here's a screenshot of how that looks like. This is, of course, assuming that you've set and granted the correct permission at the App level for that operation to occur.

I can't really remember if the workspaces used to bring that list of users back then, but I've stopped all development on this custom connector until further notice. You're more than welcome to contribute to this project and submit any pulls.
