### ISSUE TITLE
Workspace Users (Admin) Error

### ISSUE THREAD

**Issue by rhalabi** [migueesc123/PowerBIRESTAPI#97]
> I just started receiving this error today when choosing Power BI Service Administrator -> Workspace Users (Admin) table even though I am logged in as a Power BI Service Administrator.  Looks like the other tables also get same error, Dashboards (Admin), Dataflows (Admin), Reports (Admin), and Workspaces (Admin). Anyone know why?

![image](https://user-images.githubusercontent.com/53341216/149357124-8be82954-cee3-4bf7-a4c4-953c27ef6d71.png)

**Comment by rhalabi** [comment]
Thx I will wait for developer to maybe fix the .mez file. I am not too technical to update the connector with M code.

**Comment by kegauvre** [comment]
No problem. However, I didn't update de connector, I just create a new source/connection in my PowerBI... and instead of using the "Workspace User (Admin)" connector, I used the GETData connector that is already provided under the "Functions" folder (we can see this folder in your print screen).

If you want, you can add a new blank source in your powerBI and copy/paste the M code ... it should work  as a starting point for this workaround.

**Comment by klinejordan** [comment]
I can repro this, my guess is something changed with the API because I can't even make these calls in Postman. 

This will take an escalation to Microsoft to figure out

**Comment by rhalabi** [comment]
> I can repro this, my guess is something changed with the API because I can't even make these calls in Postman.
> 
> This will take an escalation to Microsoft to figure out

Thx for the reply.  Is anyone reaching out to Microsoft why this is occurring?

**Comment by rhalabi** [comment]
This looks to be working today, not sure what changed.

**Comment by rhalabi** [comment]
Just curious if any update, if anyone is working on fixing this?

**Comment by rhalabi** [comment]
This looks to be working again.  Not sure what changed.

**Comment by rhalabi** [comment]
This started occurring again today.

**Comment by klinejordan** [comment]
I can't reproduce it unfortunately, in either the connector or Postman

**Comment by rhalabi** [comment]
Very strange working ok today.
